import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sideba";

 import {Poppins} from 'next/font/google'

const poppins = Poppins({
  subsets: ["latin"],
  
  weight: [ "400","500","600"],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${poppins.className} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <SidebarTrigger />
                {children}
          </main>
        </SidebarProvider>
        
      </body>
    </html>
  );
}
